export const albumCategories = ['All', 'Streetmas', 'Outreach', 'Education', 'Health']

export const albums = [
  {
    id: 1,
    title: 'Streetmas 2.0',
    subtitle: 'Christmas Outreach · Accra 2025',
    category: 'Streetmas',
    year: '2025',
    fallback: 'from-gray-600 to-gray-900',
    images: [
      { src: '/gallery/streetmas2/1.jpg', caption: 'Streetmas 2.0 — Sharing Joy' },
      { src: '/gallery/streetmas2/2.jpg', caption: 'Meals For The Streets' },
      { src: '/gallery/streetmas2/3.jpg', caption: 'Gift Packs Ready' },
      { src: '/gallery/streetmas2/4.jpg', caption: 'Smiles All Around' },
      { src: '/gallery/streetmas2/5.jpg', caption: 'The Team in Action' },
    ],
  },
  {
    id: 2,
    title: 'Streetmas 1.0',
    subtitle: 'Sharing Love in the streets of Kumasi · 2024',
    category: 'Streetmas',
    year: '2024',
    fallback: 'from-amber-700 to-amber-950',
    images: [
      { src: '/gallery/streetmas1/1.jpg', caption: 'Streetmas 1.0 — The Beginning' },
      { src: '/gallery/streetmas1/2.jpg', caption: 'Delivering Hope on the Streets' },
      { src: '/gallery/streetmas1/3.jpg', caption: 'Every Meal Counts' },
      { src: '/gallery/streetmas1/4.jpg', caption: 'Street Youth Receiving Meals' },
      { src: '/gallery/streetmas1/5.jpg', caption: 'Celebrating Impact Together' },
    ],
  },
  {
    id: 3,
    title: 'Elite Day With the Orphans',
    subtitle: 'Adullam Orphanage · Obuasi 2023',
    category: 'Outreach',
    year: '2023',
    fallback: 'from-rose-500 to-rose-900',
    images: [
      { src: '/gallery/orphans/1.jpg', caption: 'Adullam Orphanage Visit' },
      { src: '/gallery/orphans/2.jpg', caption: 'Smiles From the Children' },
      { src: '/gallery/orphans/3.jpg', caption: 'Gift Sharing Session' },
      { src: '/gallery/orphans/4.jpg', caption: 'Interactive Education Session' },
      { src: '/gallery/orphans/5.jpg', caption: 'A Day to Remember' },
    ],
  },
  {
    id: 4,
    title: 'CKC SHS Empowerment',
    subtitle: 'Christ the King Catholic Senior High · Obuasi 2023',
    category: 'Education',
    year: '2023',
    fallback: 'from-indigo-500 to-indigo-900',
    images: [
      { src: '/gallery/ctkshs/1.jpg', caption: 'CTK SHS Empowerment Session' },
      { src: '/gallery/ctkshs/2.jpg', caption: 'WASSCE Prep — Final Year Students' },
      { src: '/gallery/ctkshs/3.jpg', caption: 'Founder Addressing the Crowd' },
      { src: '/gallery/ctkshs/4.jpg', caption: 'Distributing Educational Supplies' },
      { src: '/gallery/ctkshs/5.jpg', caption: 'Students Ready for the Future' },
    ],
  },
  {
    id: 5,
    title: 'Educational Empowerment',
    subtitle: 'School Outreach Across Obuasi · 2023',
    category: 'Education',
    year: '2023',
    fallback: 'from-orange-600 to-orange-900',
    images: [
      { src: '/gallery/education/1.jpg', caption: 'Educational Supplies Donated' },
      { src: '/gallery/education/2.jpg', caption: 'Mentorship in Session' },
      { src: '/gallery/education/3.jpg', caption: 'Books for Every Child' },
      { src: '/gallery/education/4.jpg', caption: 'Students Receiving Stationery' },
      { src: '/gallery/education/5.jpg', caption: 'Inspired to Learn' },
    ],
  },
  {
    id: 6,
    title: 'Pad a Girl Outreach',
    subtitle: 'Independence School Park · Obuasi East · May 2026',
    category: 'Health',
    year: '2026',
    fallback: 'from-purple-600 to-purple-950',
    images: [
      { src: '/gallery/padagirl/wide.JPG', caption: 'The Venue — Independence School Park' },
      { src: '/gallery/padagirl/crowd.JPG', caption: '300+ Girls in Attendance' },
      { src: '/gallery/padagirl/entrance.JPG', caption: 'Welcome to Pad a Girl' },
      { src: '/gallery/padagirl/entrance (2).JPG', caption: 'Arrival at the Venue' },
      { src: '/gallery/padagirl/backdrop.JPG', caption: 'Official Pad a Girl Backdrop' },
      { src: '/gallery/padagirl/edusession.JPG', caption: 'Menstrual Hygiene Education Session' },
      { src: '/gallery/padagirl/session.JPG', caption: 'Health Talk in Progress' },
      { src: '/gallery/padagirl/session1.JPG', caption: 'Interactive Q&A Session' },
      { src: '/gallery/padagirl/mc.JPG', caption: 'MC Hosting the Programme' },
      { src: '/gallery/padagirl/display.JPG', caption: 'Sanitary Pad Display' },
      { src: '/gallery/padagirl/display1.JPG', caption: 'Pads Ready for Distribution' },
      { src: '/gallery/padagirl/display2.JPG', caption: 'Distribution Underway' },
      { src: '/gallery/padagirl/display3.JPG', caption: 'Every Girl Receives Her Pack' },
      { src: '/gallery/padagirl/display4.JPG', caption: 'Smiles During Distribution' },
      { src: '/gallery/padagirl/display5.JPG', caption: 'Pad Distribution in Full Swing' },
      { src: '/gallery/padagirl/display6.JPG', caption: 'Empowering Every Girl' },
      { src: '/gallery/padagirl/display7.JPG', caption: 'The Last Pack Goes Out' },
      { src: '/gallery/padagirl/display (2).JPG', caption: 'Team Distributing Supplies' },
      { src: '/gallery/padagirl/display (3).JPG', caption: 'Hands Full of Impact' },
      { src: '/gallery/padagirl/display (4).JPG', caption: 'Pad a Girl in Action' },
      { src: '/gallery/padagirl/display (5).JPG', caption: 'Girls Collecting Their Packs' },
      { src: '/gallery/padagirl/culturaldisplay.JPG', caption: 'Cultural Display Performance' },
      { src: '/gallery/padagirl/dignitary.JPG', caption: 'Guest Dignitary Address' },
      { src: '/gallery/padagirl/dignitary (2).JPG', caption: 'Dignitaries in Attendance' },
      { src: '/gallery/padagirl/dignitary (3).JPG', caption: 'Special Guest Remarks' },
      { src: '/gallery/padagirl/lawyer.JPG', caption: 'Legal Advocate Speaks to Girls' },
      { src: '/gallery/padagirl/lawyer1.JPG', caption: 'Empowerment Through Knowledge' },
      { src: '/gallery/padagirl/lawyer2.JPG', caption: 'Know Your Rights Session' },
      { src: '/gallery/padagirl/lawyerentry.JPG', caption: 'Advocate Arriving at the Event' },
      { src: '/gallery/padagirl/G.Acheampong.JPG', caption: 'Godfred Acheampong Foundation — Our Partner' },
      { src: '/gallery/padagirl/G.Acheampong1.JPG', caption: 'Partners Supporting the Cause' },
      { src: '/gallery/padagirl/klint.JPG', caption: 'Founder Clinton Klint Addressing the Crowd' },
      { src: '/gallery/padagirl/dd.JPG', caption: 'Special Moment at Pad a Girl' },
      { src: '/gallery/padagirl/wide1.JPG', caption: 'Full Hall — Packed Programme' },
      { src: '/gallery/padagirl/wide3.JPG', caption: 'The Crowd Engaged' },
      { src: '/gallery/padagirl/wide4.JPG', caption: 'A Sea of Young Girls' },
      { src: '/gallery/padagirl/wide5.JPG', caption: 'Community Turnout' },
      { src: '/gallery/padagirl/wide6.JPG', caption: 'Wide View of the Event' },
      { src: '/gallery/padagirl/wide (2).JPG', caption: 'The Full Programme in Session' },
      { src: '/gallery/padagirl/wide (3).JPG', caption: 'Girls Listening Attentively' },
      { src: '/gallery/padagirl/wide (4).JPG', caption: 'Massive Attendance' },
      { src: '/gallery/padagirl/wide (5).JPG', caption: 'Obuasi East Shows Up' },
      { src: '/gallery/padagirl/wide (6).JPG', caption: 'Stage View of the Audience' },
      { src: '/gallery/padagirl/wide (7).JPG', caption: 'Standing Room Only' },
      { src: '/gallery/padagirl/wide (8).JPG', caption: 'Full House at Independence Park' },
      { src: '/gallery/padagirl/vgroup.JPG', caption: 'Volunteer Team Group Photo' },
      { src: '/gallery/padagirl/group1.JPG', caption: 'Group Photo — Girls & Team' },
      { src: '/gallery/padagirl/group2.JPG', caption: 'Smiles All Round' },
      { src: '/gallery/padagirl/group3.JPG', caption: 'Together We Inspire' },
      { src: '/gallery/padagirl/group4.JPG', caption: 'Girls of Obuasi East' },
      { src: '/gallery/padagirl/group5.JPG', caption: 'The Foundation Team' },
      { src: '/gallery/padagirl/group6.JPG', caption: 'Partners & Team Together' },
      { src: '/gallery/padagirl/group7.JPG', caption: 'A Moment to Remember' },
      { src: '/gallery/padagirl/group8.JPG', caption: 'Klint Inspires Africa Family' },
      { src: '/gallery/padagirl/group9.JPG', caption: 'End of a Successful Day' },
      { src: '/gallery/padagirl/1.jpg', caption: 'Pad a Girl — Captured Moments' },
    ],
  },
]
