export const albumCategories = ['All', 'Streetmas', 'Outreach', 'Education', 'Health']

export const albums = [
  {
    id: 1,
    title: 'Streetmas 2.0',
    subtitle: 'Christmas Outreach · Accra 2025',
    category: 'Streetmas',
    year: '2025',
    fallback: 'from-gray-600 to-gray-900',
    images: [
      { src: '/gallery/streetmas2/1.jpg', caption: 'Streetmas 2.0 — Sharing Joy' },
      { src: '/gallery/streetmas2/2.jpg', caption: 'Meals For The Streets' },
      { src: '/gallery/streetmas2/3.jpg', caption: 'Gift Packs Ready' },
      { src: '/gallery/streetmas2/4.jpg', caption: 'Smiles All Around' },
      { src: '/gallery/streetmas2/5.jpg', caption: 'The Team in Action' },
    ],
  },
  {
    id: 2,
    title: 'Streetmas 1.0',
    subtitle: 'Sharing Love in the streets of Kumasi · 2024',
    category: 'Streetmas',
    year: '2024',
    fallback: 'from-amber-700 to-amber-950',
    images: [
      { src: '/gallery/streetmas1/1.jpg', caption: 'Streetmas 1.0 — The Beginning' },
      { src: '/gallery/streetmas1/2.jpg', caption: 'Delivering Hope on the Streets' },
      { src: '/gallery/streetmas1/3.jpg', caption: 'Every Meal Counts' },
      { src: '/gallery/streetmas1/4.jpg', caption: 'Street Youth Receiving Meals' },
      { src: '/gallery/streetmas1/5.jpg', caption: 'Celebrating Impact Together' },
    ],
  },
  {
    id: 3,
    title: 'Elite Day With the Orphans',
    subtitle: 'Adullam Orphanage · Obuasi 2023',
    category: 'Outreach',
    year: '2023',
    fallback: 'from-rose-500 to-rose-900',
    images: [
      { src: '/gallery/orphans/1.jpg', caption: 'Adullam Orphanage Visit' },
      { src: '/gallery/orphans/2.jpg', caption: 'Smiles From the Children' },
      { src: '/gallery/orphans/3.jpg', caption: 'Gift Sharing Session' },
      { src: '/gallery/orphans/4.jpg', caption: 'Interactive Education Session' },
      { src: '/gallery/orphans/5.jpg', caption: 'A Day to Remember' },
    ],
  },
  {
    id: 4,
    title: 'CKC SHS Empowerment',
    subtitle: 'Christ the King Catholic Senior High · Obuasi 2023',
    category: 'Education',
    year: '2023',
    fallback: 'from-indigo-500 to-indigo-900',
    images: [
      { src: '/gallery/ctkshs/1.jpg', caption: 'CTK SHS Empowerment Session' },
      { src: '/gallery/ctkshs/2.jpg', caption: 'WASSCE Prep — Final Year Students' },
      { src: '/gallery/ctkshs/3.jpg', caption: 'Founder Addressing the Crowd' },
      { src: '/gallery/ctkshs/4.jpg', caption: 'Distributing Educational Supplies' },
      { src: '/gallery/ctkshs/5.jpg', caption: 'Students Ready for the Future' },
    ],
  },
  {
    id: 5,
    title: 'Educational Empowerment',
    subtitle: 'School Outreach Across Obuasi · 2023',
    category: 'Education',
    year: '2023',
    fallback: 'from-orange-600 to-orange-900',
    images: [
      { src: '/gallery/education/1.jpg', caption: 'Educational Supplies Donated' },
      { src: '/gallery/education/2.jpg', caption: 'Mentorship in Session' },
      { src: '/gallery/education/3.jpg', caption: 'Books for Every Child' },
      { src: '/gallery/education/4.jpg', caption: 'Students Receiving Stationery' },
      { src: '/gallery/education/5.jpg', caption: 'Inspired to Learn' },
    ],
  },
  {
    id: 6,
    title: 'Pad a Girl Outreach',
    subtitle: 'Independence School Park · Obuasi East · May 2026',
    category: 'Health',
    year: '2026',
    fallback: 'from-purple-600 to-purple-950',
    images: [
      { src: '/gallery/padagirl/1.jpg', caption: 'Pad a Girl — Hygiene Education' },
      { src: '/gallery/padagirl/2.jpg', caption: 'Sanitary Pads Distribution' },
      { src: '/gallery/padagirl/3.jpg', caption: 'Health Talk in Session' },
      { src: '/gallery/padagirl/4.jpg', caption: 'JHS Girls Empowered' },
      { src: '/gallery/padagirl/5.jpg', caption: 'Partners in Impact' },
    ],
  },
]
